---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8888}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[phpipam::app_db]
      - recipe[phpipam::app_site]
